spring:
    application: 
        name: creature-service
    datasource:
        url: ${JDBC_URL}
        username: ${JDBC_USER}
        password: ${JDBC_PASS}
        driver-class-name: oracle.jdbc.driver.OracleDriver
        platform: oracle
    jpa:
        database: ORACLE
        show-sql: true
        database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            ddl-auto: none
server:
    port: 3434

logging:
  file: /logs/Application.log
  level:
    com.rpgSuite.creature: DEBUG
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  